# Generated by Django 4.2.3 on 2023-08-02 23:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=60, unique=True)),
                ('born_date', models.DateField(null=True)),
                ('phone', models.CharField(max_length=14, null=True)),
                ('dni', models.CharField(max_length=8, null=True, unique=True)),
                ('province', models.CharField(max_length=50, null=True)),
                ('city', models.CharField(max_length=250, null=True)),
                ('address', models.CharField(max_length=140, null=True)),
                ('date_joined', models.DateField(default=datetime.datetime(2023, 8, 2, 23, 31, 43, 43517, tzinfo=datetime.timezone.utc), verbose_name='date joined')),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
