# Generated by Django 3.1 on 2020-08-13 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField(default=0)),
                ('cvu', models.CharField(default=None, max_length=22, null=True, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transferencias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_sended', models.CharField(default='', max_length=50)),
                ('cash_losed', models.CharField(default='', max_length=50)),
                ('date', models.CharField(default='', max_length=60)),
                ('from_cvu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_cvu', to='banking.banking')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to=settings.AUTH_USER_MODEL)),
                ('to_cvu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_cvu', to='banking.banking')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_moved', models.CharField(default='', max_length=50)),
                ('type_of_move', models.CharField(default='', max_length=50)),
                ('date', models.CharField(default='', max_length=60)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
