# Generated by Django 3.1 on 2020-08-18 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='cash_moved',
            field=models.FloatField(default=0),
        ),
    ]
