# Generated by Django 4.2.3 on 2023-07-29 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banking',
            name='cvu',
            field=models.CharField(editable=False, max_length=22, unique=True),
        ),
    ]
