# Generated by Django 3.1 on 2020-08-18 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0002_auto_20200818_0102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transferencias',
            name='cash_losed',
        ),
        migrations.RemoveField(
            model_name='transferencias',
            name='cash_sended',
        ),
        migrations.AddField(
            model_name='transferencias',
            name='cash_moved',
            field=models.FloatField(default=0),
        ),
    ]
