# Generated by Django 3.0.7 on 2020-07-31 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0002_auto_20200731_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banking',
            name='balance',
            field=models.FloatField(default=0),
        ),
    ]
