# Generated by Django 3.0.7 on 2020-07-31 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0004_auto_20200731_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banking',
            name='cvu',
            field=models.CharField(default=None, max_length=22, null=True, unique=True),
        ),
    ]
