# Generated by Django 3.0.7 on 2020-08-01 03:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('banking', '0005_auto_20200731_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_sended', models.FloatField(default=None)),
                ('from_cvu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_cvu', to='banking.Banking')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to=settings.AUTH_USER_MODEL)),
                ('to_cvu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_cvu', to='banking.Banking')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
