# Generated by Django 3.0.7 on 2020-08-01 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0007_auto_20200801_0400'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferencias',
            name='cash_losed',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='transferencias',
            name='cash_sended',
            field=models.CharField(default='', max_length=50),
        ),
    ]
