# Generated by Django 3.0.7 on 2020-08-01 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0008_auto_20200801_0421'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='type_of_move',
            field=models.CharField(default='', max_length=50),
        ),
    ]
