# Generated by Django 3.0.7 on 2020-08-01 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0009_transactions_type_of_move'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='date',
            field=models.CharField(default='2020-08-01 05:46:02.335326', max_length=60),
        ),
        migrations.AddField(
            model_name='transferencias',
            name='date',
            field=models.CharField(default='2020-08-01 05:46:02.334009', max_length=60),
        ),
    ]
