# Generated by Django 3.0.7 on 2020-08-02 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0011_auto_20200801_0302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='date',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='transferencias',
            name='date',
            field=models.CharField(default='', max_length=60),
        ),
    ]
